name: Fly Deploy
on:
  pull_request:
    types:
      - closed
jobs:
  deploy_db:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy_db') }}
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./businesstrips-db
  deploy_backend:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy_backend') }}
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --env=CORS_ALLOWED_ORIGIN=${{ vars.FRONTEND_URL }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./businesstrips-backend
  deploy_frontend:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy_frontend') }}
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg=BACKEND_URL=${{ vars.BACKEND_URL }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./businesstrips-frontend
